version: '3.3'

# ELK + Filebeat
services:
  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    restart: unless-stopped
    networks:
      - netElk
  kibana:
    image: kibana:7.9.2
    container_name: kibana
    ports:
      - 5601:5601
    restart: unless-stopped
    networks:
      - netElk
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:7.8.0
    container_name: logstash
    ports:
      - 5044:5044
    restart: unless-stopped
    networks:
      - netElk
    depends_on:
      - elasticsearch
    volumes:
      - ./config/logstash/:/usr/share/logstash/pipeline/
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.8.1
    container_name: filebeat
    networks:
      - netElk
    depends_on:
      - logstash
    volumes:
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
networks:
  netElk:
    driver: bridge
