{
 "title": "Host Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "% CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Disk Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} ) / (node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) ))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1073741824 \n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}